main: yy.zacharyguard.yeyadisp.Main
name: YeyaDisp
version: 0.2.2
author: Zachary Guard
description: Gourd.
commands:
  yeyadisp:
    aliases: [ydisp]
    description: Manage YeyaDisp.
    usage: /ydisp OR /ydisp disable
    permission: bukkit.op
    permission-message: Only ops (those with bukkit.op permission) can use YeyaDisp.