main: yy.zacharyguard.yeyadisp.Main
name: YeyaDisp
version: 0.0.0
author: Zachary Guard
description: Gourd.
commands:
  yeyadisp:
    description: Make a dispenser infinite.
    usage: /yeyadisp
    permission: bukkit.op
    permission-message: Only ops (those with bukkit.op permission) are authorized to use YeyaDisp.